name: Notificar Discord

on:
  push:
    branches:
      - oliveira

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commit para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "ðŸ“¢ Changelogs",
              "description": "",
              "color": 3066993,
              "thumbnail": {
                "url": \"https://media.discordapp.net/attachments/1405539658242195456/1410440115343593513/concluido.gif?ex=68b10638&is=68afb4b8&hm=328315e872e4d05e262df0830b85a75f61552b375476cf56fa862151c9d6a1ab&=\"
              },
              "fields": [
                {
                  "name": "â­ Autor",
                  "value": "> ${{ github.actor }}"
                },
                {
                  "name": "ðŸ“ VersÃ£o atualizada",
                  "value": "> ${{ github.event.head_commit.message }}"
                },
                {
                  "name": "ðŸ”— Commit",
                  "value": "> ${{ github.event.head_commit.url }}"
                }
              ]
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
