name: Notificar Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commit para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "ğŸ“¢ Changelogs",
              "description": "**${{ github.actor }}**",
              "color": 5814783,
              "fields": [
                {
                  "name": "ğŸ“ VersÃ£o atualizada",
                  "value": "${{ github.event.head_commit.message }}"
                },
                {
                  "name": "ğŸ”— Commit",
                  "value": "${{ github.event.head_commit.url }}"
                }
              ]
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
