name: Notificar Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commit para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "ðŸ“Œ Novo Commit no GitHub",
              "description": "Um push foi feito pelo usuÃ¡rio ${{ github.actor }}",
              "color": 5814783,
              "fields": [
                {
                  "name": "Mensagem do Commit",
                  "value": "${{ github.event.head_commit.message }}"
                },
                {
                  "name": "Branch",
                  "value": "${{ github.ref }}"
                },
                {
                  "name": "Link do Commit",
                  "value": "${{ github.event.head_commit.url }}"
                }
              ]
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
