name: Notificar Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar commit para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "ðŸ“¢ Changelogs",
              "description": "",
              "color": 6710918,
              "fields": [
                {
                  "name": "â­ Autor",
                  "value": "> ${{ github.actor }}"
                },
                {
                  "name": "ðŸ“ VersÃ£o atualizada",
                  "value": "> ${{ github.event.head_commit.message }}"
                },
                {
                  "name": "ðŸ”— Commit",
                  "value": "> ${{ github.event.head_commit.url }}"
                }
              ]
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
